### ISSUE TITLE
Some suggestions on CMake file

### ISSUE THREAD

**Issue by thealexparshin** [piscisaureus/wepoll#12]
(I really admire your work! It's exactly what we need here.)

1) I had to add at the end of CMakeLists.txt some installation instructions:

file (GLOB includeFiles "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h")
INSTALL(FILES ${includeFiles} DESTINATION include)
INSTALL(TARGETS ${DLL_TARGET} RUNTIME DESTINATION bin LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)

2) Ideally, if build produced two libraries, static and dynamic. I needed a static library, so I did dirty conversion:

-set(DLL_TARGET "${HEADER_NAME}.dll")
-add_library(${DLL_TARGET} SHARED ${SOURCES_HEADER} ${SOURCES_SRC} ${SOURCES_SRC_REGULAR})
+set(DLL_TARGET "${HEADER_NAME}")
+add_library(${DLL_TARGET} ${SOURCES_HEADER} ${SOURCES_SRC} ${SOURCES_SRC_REGULAR})

This also allowed removing library source files from linking to tests. Otherwise, they are recompiled for each test.

3) If you could re-define epoll HANDLE to be SOCKET, it would be easier for {*nix, Windows} portable code. On *nix, you normally define SOCKET as int, and many things become more readable. 

4) I'm attaching minimal 
[FindEPoll.cmake.txt](https://github.com/piscisaureus/wepoll/files/2743878/FindEPoll.cmake.txt) file, if you're interested. Just remove .txt suffix from its name.

**Comment by piscisaureus** [comment]
Sorry for ignoring this for so long.

I'm actually not so interested in maintaining a CMAKE file for public consumption, or any build system configuration for that matter. There are too many of them and everyone has different requirements.

My general recommendation is to use the all-in-one wepoll.c from the [dist branch](https://github.com/piscisaureus/wepoll/tree/dist). I think it's easy enough for skilled engineers to compile that into the format they prefer.
