### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by baticag** [piscisaureus/wepoll#15]
Hey,

Is there anyway to add support for Windows XP? Many users still use it here.

Thanks

**Comment by piscisaureus** [comment]
The problems with supporting XP are the following:
  * XP doesn't have the `CancelIoEx()`, API which makes it impossible to cancel a `IOCTL_AFD_POLL` operation, which is necessary when `epoll_ctl(..., EPOLL_CTL_MOD, ...)` is called to change the interest flags on a particular socket.
  * XP doesn't support the `WSAIoctl(..., SIO_BASE_SOCKET, ...)` API to look up the BSP handle for a socket in the presence of layered service providers.

[Libuv](https://github.com/libuv/libuv)'s `uv_poll` API uses a similar technique as wepoll does and it does support XP. It does so by setting the `Exclusive` flag on `IOCTL_AFD_POLL` operations, so whenever you submit a new poll operation, the previous one is automatically cancelled. The downside of course is that you lose the ability to poll the same socket with multiple epoll instances at the same time. In lieu of `SIO_BASE_SOCKET` it also implements a (very inefficient) fallback mechanism that uses threads and `select()` to support those systems that have LSPs installed.

So, while it would be possible to provide limited XP support, it would take a lot of time to implement and also increase code size and complexity a lot.
I have no time nor the interest to do this work. Feel free to give it a go, though.
