### ISSUE TITLE
epoll_ctl(epfd, EPOLL_CTL_ADD, m_fd, &ev) get an error

### ISSUE THREAD

**Issue by MacroGu** [piscisaureus/wepoll#16]
when i call epoll_ctl(epfd, EPOLL_CTL_ADD, m_fd, &ev) while pass same m_fd ,  it return -1, 
I getlasterror, and it is 183
but I run same condition under linux , everything is ok, please help for fix it, thanks

**Comment by bnoordhuis** [comment]
If 183 maps to `EEXIST` then it looks correct to me, that's what `epoll_ctl()` returns on Linux when you try to register the same file descriptor twice.

**Comment by MacroGu** [comment]
thanks.

**Comment by AlanBateman** [comment]
How does wepoll work with a sequence of EPOLL_CTL_ADD, EPOLL_CTL_DEL, EPOLL_CTL_ADD for the same socket? It appears to me that the second EPOLL_CTL_ADD fails with EEXIST whereas on Linux it will succeeds. It's as if the DEL wasn't successful even though it return epoll_ctl returned 0.
