### ISSUE TITLE
Use NT reserve objects

### ISSUE THREAD

**Issue by DemiMarie-parity** [piscisaureus/wepoll#18]
https://wj32.org/wp/2010/07/18/the-nt-reserve-object/

**Comment by piscisaureus** [comment]
Where / how would that be used?

**Comment by DemiMarie-parity** [comment]
To avoid late failures in low-memory conditions.  They can be used for NtSetIoCompletionEx, for example.

**Comment by piscisaureus** [comment]
wepoll doesn't use NtSetIoCompletionEx.

> To avoid late failures in low-memory conditions. 

Has this been an issue when using wepoll?

**Comment by DemiMarie-parity** [comment]
Closing as there is nothing to do.
