### ISSUE TITLE
License is weird.

### ISSUE THREAD

**Issue by nicolasnoble** [piscisaureus/wepoll#2]
Are you sure the part about "Google Inc." belongs in there ?

https://github.com/piscisaureus/epoll_windows/blob/master/LICENSE#L13

**Comment by piscisaureus** [comment]
@nicolasnoble 
Thanks for letting me know - copypasta fail. It should be fixed now.
Do you want to use this library, or are you just monitoring licenses for google?

**Comment by nicolasnoble** [comment]
Ah, sorry, didn't notice your reply before.

I was merely interested in the hack you are using to access the AFD. I could be tempted to use your code if the AFD layer was separated from the rest of the epoll interface, since this is the only part I'd use.
