### ISSUE TITLE
epoll_ctl: Access Denied

### ISSUE THREAD

**Issue by WeaponMan** [piscisaureus/wepoll#21]
I am trying to run this on Windows Vista, but when I call epoll_ctl I get -1 and the error comming from winapi is Access Denied.
I guess the NtCreateFile function returns with that status.
I am not really sure if this supported on Vista.

**Comment by piscisaureus** [comment]
Unfortunately your bug report contains no information other than epoll_ctl() returns -1 and the fact that you're using windows vista...

* How did you determine that this is an issue with wepoll and not with your own code (does it run fine on another system)?
* How did you determine that NtCreateFile is the failing syscall (stepped through the code)?
* How did you determine it had anything to do with windows Vista? (ok -- you already said that you didn't)

I'm going to close this issue as there is nothing I can do.

Feel free to open a new issue that contains - at a minimum - what I need to know to be able to reproduce this issue. 
Also read some of [this](https://www.google.com/search?q=how+to+write+a+good+bug+report).

**Comment by piscisaureus** [comment]
> I am not really sure if this supported on Vista.

I claim that it is in the README, and at some point in history it did work on Vista.
But the library is not regularly tested on this old version of windows, so I might change it it to Windows 7 where it does work.
