### ISSUE TITLE
Proxifier CI is borked

### ISSUE THREAD

**Issue by njsmith** [piscisaureus/wepoll#22]
FYI, proxifier just [released a new version](https://www.proxifier.com/changelog/), and apparently it doesn't use an LSP anymore?

Quick fix: https://github.com/python-trio/trio/pull/1780

**Comment by piscisaureus** [comment]
@njsmith Thanks for the heads up! After clearing the AppVeyor cache I this my CI went red as well.

I opted to put the LSP installers in a gist and download them from there: https://github.com/piscisaureus/wepoll/commit/183993f30f48d9daec0230c52eb48a96f26982d1.
