### ISSUE TITLE
compile wepoll failed on vs2010

### ISSUE THREAD

**Issue by gozfree** [piscisaureus/wepoll#26]
hi piscisaureus,
My env is vs2010 on win10, I meet link error:
"wepoll.obj : error LNK2019: unresolved external symbol _InterlockedAdd referenced in function _reflock_ref"
what static lib should I add into project?
Many thanks

**Comment by piscisaureus** [comment]
`_InterlockedAdd` is a compiler intrinsic. 
You might need to enable them with the `/Oi` flag, although VS2010 is very old and I don't remember whether it supports it.
