### ISSUE TITLE
Multi-Threading problems with epoll_wait

### ISSUE THREAD

**Issue by phit666** [piscisaureus/wepoll#28]
Calling epoll_wait in multi threads without using any thread locks will give each thread the same events so only the first thread will succeed and the rest will fail because the events are already handled in the first thread that executed the events. Now putting thread lock before calling epoll_wait will work but that is not really multi-threading, GetQueuedCompletionStatus/eX should be called by several threads at the same time, without any thread locks before the call so each thread will be in waiting mode (at the same time) for the events to arrive, doing so multi-threading will now make sense as GetQueuedCompletionStatus/eX is designed like this.

**Comment by piscisaureus** [comment]
The same behavior can be observed on linux when you call epoll_wait() concurrently from multiple threads.

If it is a problem for your application I'd suggest to use the EPOLLONESHOT flag.
