### ISSUE TITLE
why use InterlockedAdd，but not _InterlockedExchangeAdd ?

### ISSUE THREAD

**Issue by joyongzhu** [piscisaureus/wepoll#29]
I first learned about WEPOLL project because of libzmq compilation problems, i change InterlockedAdd to InterlockedExchangeAdd , and libzmq can work on x64.

then i read windows docs: [interlockedexchangeadd](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedexchangeadd-intrinsic-functions?view=msvc-170), [interlockedadd](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedadd-intrinsic-functions?view=msvc-170)

InterlockedAdd Architecture is ARM, ARM64
_InterlockedExchangeAdd Architecture is x86, ARM, x64, ARM64

so i want to know why WEPOLL don't use _InterlockedExchangeAdd to support more Architecture?

**Comment by piscisaureus** [comment]
No reason - when I wrote it I don't think these functions were around. I'd land a patch that changes this if it doesn't break other supported architectures/compilers.

**Comment by joyongzhu** [comment]
OK，I understand，thanks~
