### ISSUE TITLE
Wepoll may lose interest list entries when the OS reuses a socket descriptor

### ISSUE THREAD

**Issue by djelinski** [piscisaureus/wepoll#34]
### Background:
We are using wepoll in multiple threads; one thread runs epoll_wait in a loop, and schedules completion actions to run in response to received events. Other threads register interest ops using epoll_ctl with EPOLL_CTL_MOD first, and if that fails with ENOENT, retrying with EPOLL_CTL_ADD.
The above scheme usually serves us well, but occasionally some events (usually related to `connect`) are lost.

### The problem:

This happens when the socket we use with `connect` is assigned the same `SOCKET` value as a recently closed socket, and the sequence of events is exactly right:
- old socket is closed
- new socket is created, connect and epoll_ctl are issued
- the poller thread receives `AFD_POLL_LOCAL_CLOSE` for the previous socket, and deletes all state associated with the `SOCKET` handle.

Normally this reproduces 1 in 10k-100k times. By adding a `Sleep(30)` before [this line](https://github.com/piscisaureus/wepoll/blob/0598a791bf9cbbf480793d778930fc635b044980/wepoll.c#L1230) we can make it reproduce every time.

Can this be fixed in wepoll, or do we need to change the way we use it?

**Comment by piscisaureus** [comment]
To avoid race conditions like this, follow the recommendation from the [readme](https://github.com/piscisaureus/wepoll#epoll_ctl):
> always explicitly remove a socket from its epoll set using `EPOLL_CTL_DEL` before closing the socket.

**Comment by djelinski** [comment]
Thanks for the hint!
