### ISSUE TITLE
Why 32 socket limit per AFD handle?

### ISSUE THREAD

**Issue by bradh352** [piscisaureus/wepoll#40]
In the code, POLL_GROUP__MAX_GROUP_SIZE = 32 :
https://github.com/piscisaureus/wepoll/blob/0598a791bf9cbbf480793d778930fc635b044980/wepoll.c#L946C9-L946C35

This causes it to create another AFD handle for every 32 sockets which seems to add a lot of complexity.  Is there an actual known limit?  Does it vary on different Windows versions?

I tested with 64, 128 and 512 sockets in an implementation I'm working on for c-ares and I appeared to properly receive events on each and every socket as expected.  That said, I was testing on Windows 11 ARM64 in a VM on a MacBook.

My implementation for reference is here: https://github.com/c-ares/c-ares/pull/811/files
(we were previously using an implementation closer to what libuv uses, but ran into some odd crashes, this methodology seems more stable).

We have automated tests to compile with MSVC, Clang, and GCC, and even run it under ASAN and UBSAN and nothing appears to report any sort of issue when using greater than 32 connections.

I'm currently not putting a limit in my implementation so regardless of how many sockets we have, we're enqueuing the poll events to the same AFD handle.   I don't really have the ability to test older Windows versions, so any insight would be appreciated!

**Comment by piscisaureus** [comment]
This comment has the context: https://github.com/python-trio/trio/issues/52#issuecomment-548215128

**Comment by bradh352** [comment]
Oh interesting.  Not at all what I expected.  Sounds like its worthwhile to do then, thanks for the insight!

**Comment by bradh352** [comment]
I might also mention based on the testing performance for cancel in that referenced ticket, a value like 128 or 256 might be more "optimal".
