### ISSUE TITLE
LSP compatibility

### ISSUE THREAD

**Issue by bnoordhuis** [piscisaureus/wepoll#6]
Huibertje, is wepoll expected to work in the presence of LSPs?  I suspect the answer is 'no' and in that case the readme could list that under 'Limitations.'

**Comment by piscisaureus** [comment]
It's supposed to work.
However there is known bug- see #5
And a "fix" that I don't want to land:
https://github.com/piscisaureus/wepoll/commit/4e149da8ba6134660974f6e0d581b4393d38ee11

(FYI the same bug is present in libuv - it switched to slow mode when it
shouldn't. Somebody reported this at some point but I forgot the details
and never fixed it.)

 Anyway, wepoll should just work, unless you use some exotic type of
socket. Tcp/udp ip/ip6 etc are fine.

**Comment by bnoordhuis** [comment]
Okay, good to know.  I'll go ahead and close this out then.

**Comment by linusyang** [comment]
@piscisaureus Hello! I tried to [rewrite](https://github.com/linusyang92/wepoll/commit/d394299e965b0296a557382a18ed619a822b508a) your previous LSP patch using RB tree for faster search. The new patch can be found in the [LSP branch](https://github.com/linusyang92/wepoll/tree/lsp) of my repo. I wonder if the performance could be improved.
